version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:14.15.5
    environment:
      USER: circleci

  poke_npmrc: &poke_npmrc
    run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

  save_npm_cache: &save_npm_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  ci:
    <<: *container_config
    steps:
      - *poke_npmrc
      - checkout
      - *restore_npm_cache
      - run: npm install
      - run: npm test
      - *save_npm_cache

  live:
    <<: *container_config
    steps:
      - *poke_npmrc
      - checkout
      - *restore_npm_cache
      - run: npm install
      - *save_npm_cache
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - ci
      - live:
          requires:
            - ci
          filters:
            branches:
              only: master
